# Generated by Django 5.1.7 on 2025-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='frontend/my-react-app/public/images/sample.jpg', null=True, upload_to=''),
        ),
    ]
