# Generated by Django 5.1.7 on 2025-05-27 11:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placehoder', max_length=255, verbose_name='image'),
        ),
    ]
